# ================================
# Docker Compose para Forji Backend
# ================================

version: '3.8'

services:
  # ================================
  # Banco de Dados PostgreSQL
  # ================================
  postgres:
    image: postgres:15-alpine
    container_name: forji-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forji_db
      POSTGRES_USER: forji_user
      POSTGRES_PASSWORD: forji_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - forji-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U forji_user -d forji_db']
      interval: 10s
      timeout: 5s
      retries: 5

  # ================================
  # Aplicação Backend (Produção)
  # ================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: forji-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://forji_user:forji_password@postgres:5432/forji_db

      # JWT
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d

      # Application
      NODE_ENV: production
      PORT: 3001

      # CORS
      FRONTEND_URL: http://localhost:3000

      # Rate Limiting
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 10
    ports:
      - '3001:3001'
    networks:
      - forji-network
    volumes:
      # Mount do schema do Prisma para migrations em runtime se necessário
      - ./prisma:/app/prisma:ro
    healthcheck:
      test: ['CMD', 'node', '--version']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ================================
  # Aplicação Backend (Desenvolvimento)
  # ================================
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: forji-backend-dev
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://forji_user:forji_password@postgres:5432/forji_db

      # JWT
      JWT_SECRET: dev-secret-key
      JWT_EXPIRES_IN: 24h

      # Application
      NODE_ENV: development
      PORT: 3001

      # CORS
      FRONTEND_URL: http://localhost:3000
    ports:
      - '3001:3001'
      - '9229:9229' # Debug port
    networks:
      - forji-network
    volumes:
      # Mount do código para hot reload
      - .:/app
      - /app/node_modules
      - /app/dist
    command: npm run start:debug
    profiles:
      - development

# ================================
# Volumes
# ================================
volumes:
  postgres_data:
    driver: local

# ================================
# Networks
# ================================
networks:
  forji-network:
    driver: bridge
