version: "3.8"
services:
  db:
    image: postgres:16
    container_name: forge_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forge_db
      POSTGRES_USER: forge_user
      POSTGRES_PASSWORD: forge_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
